DROP VIEW IF EXISTS "HISTORICAL_LOCATIONS" CASCADE;
CREATE VIEW "HISTORICAL_LOCATIONS" AS
SELECT
    t.id AS "ID",
    NULL::timestamptz AS "TIME",
    t.id AS "THING_ID",
    1::bigint AS "LOCATION_ID"
FROM thing t;
