{
 "title": "Last Observations",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "select schema_name from get_latest_observation_all_schemas() order by result_time desc;"
   },
   {
    "name": "period",
    "label": "Period",
    "query": "1 day, 2 days, 4 days, 1 week, 2 weeks, 1 month"
   },
   {
    "name": "ingest_type",
    "label": "Ingest Type",
    "query": "select \n    ingest_type as __text,\n    array_agg(schema_name) as __value\nfrom get_latest_observation_by_ingest_type_all_schemas('$period')\nwhere last_result_time < now()\ngroup by ingest_type\norder by max(last_result_time) desc"
   },
   {
    "name": "current_project",
    "label": "Project",
    "query": "select \n    schema_name as __text,\n    array_agg(ingest_type) as __value\nfrom get_latest_observation_by_ingest_type_all_schemas('$period')\nwhere last_result_time < now()\ngroup by schema_name\norder by max(last_result_time) desc"
   }
  ]
 },
 "panels": [
  { "title": "Table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "WITH last_obs AS (\n  SELECT * FROM get_latest_observation_all_schemas()\n  WHERE schema_name in ($project)\n)\nSELECT \n  schema_name as \"Projekt\",\n  result_time as \"Letzter Datenpunkt\",\n  EXTRACT(EPOCH FROM (NOW() - result_time)) as \"Sekunden seit letztem Wert\",\n  NOW() - result_time as \"Zeit seit letztem Wert\",\n  CASE \n    WHEN NOW() - result_time < INTERVAL '6 hour' THEN '🟢 Aktuell'\n    WHEN NOW() - result_time < INTERVAL '24 day' THEN '🟡 Fast aktuell'\n    WHEN NOW() - result_time < INTERVAL '48 days' THEN '🟠 Verzögert'\n    ELSE '🔴 Alt'\n  END as \"Status\"\nFROM last_obs\n\nORDER BY result_time DESC;"
    }
   ]
  },
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "options": {
    "content": "The variables `Ingest Type` and `Project` are queried from the database.\n\nWe only see Ingest Types and Project names where the latest Observation is no older than `Period`."
   }
  },
  { "title": "By Ingest Type", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "$ingest_type",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "repeat": "ingest_type",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MIN(extract(epoch FROM now() - last_result_time)::bigint) AS seconds_since_last\nFROM get_latest_observation_by_ingest_type_all_schemas()\nWHERE last_result_time < NOW()\nGROUP BY ingest_type\nHAVING ingest_type = '${ingest_type:text}'"
    }
   ]
  },
  {
   "title": "$ingest_type",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 8 },
   "repeat": "ingest_type",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  schema_name as metric,\n  extract(epoch FROM now() - last_result_time)::bigint AS value\nFROM get_latest_observation_by_ingest_type_all_schemas()\nWHERE ingest_type = '${ingest_type:text}'\nand last_result_time < now()\norder by last_result_time desc"
    }
   ]
  },
  { "title": "By Project", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "$current_project",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 39 },
   "repeat": "current_project",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MIN(extract(epoch FROM now() - last_result_time)::bigint) AS seconds_since_last\nFROM get_latest_observation_by_ingest_type_all_schemas()\nWHERE last_result_time < NOW()\nGROUP BY schema_name\nHAVING schema_name = '${current_project:text}'"
    }
   ]
  },
  {
   "title": "$current_project",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 39 },
   "repeat": "current_project",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ingest_type as metric,\n  extract(epoch FROM now() - last_result_time)::bigint AS value\nFROM get_latest_observation_by_ingest_type_all_schemas()\nWHERE schema_name = '${current_project:text}'\nand last_result_time < now()\norder by last_result_time desc"
    }
   ]
  },
  {
   "title": "All Projects",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "$project",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 76 },
     "repeat": "project",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  extract(epoch FROM now() - result_time)::bigint AS seconds_since_last\nFROM get_latest_observation_all_schemas()\nWHERE schema_name = ${project:singlequote}"
      }
     ]
    }
   ]
  }
 ]
}